variables:
  project_name: 'GloboImprensa'
  netcore_version: '2.2'

jobs:
  - job: Build
    steps:
      - script: | 
         dotnet restore
         dotnet publish GloboChallenge.sln -c Release

  - job: Test
    dependsOn: Build
    steps:
      - script: | 
          dotnet test GloboChallenge.sln


              
      # - task: MSBuild@1
      #   inputs:
      #     solution: '**/*.sln'

  