variables:
  project_name: 'GloboImprensa'
  netcore_version: '2.2'

jobs:
  - job: Build
    steps:
      - script: | 

          # pwd && ls -la
          # dotnet restore
          # dotnet publish -c Release -o bin/Release/netcoreapp$(netcore_version)
          # mkdir artifact
          # cp -r $(project_name)/bin/Release/netcore$(netcore_version) artifact/$(Build.SorceBrancName)

        # displayName: Build Application
        # - task: PublishPipelineArtifact@1
        # displayName: Store Application Artifact
        # inputs:
        #   path: $(System.DefaultWorkingDirectory)/artifact
        #   artifact: $(project_name)
              
      - task: MSBuild@1
        inputs:
          solution: '**/*.sln'

      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
          vsVersion: '16.0'


  

  